- id: sourcery
  name: sourcery
  description: Magically refactor Python
  language: python
  additional_dependencies: [sourcery-cli==0.8.4]
  entry: sourcery refactor --check
  require_serial: true
  types: [python]
