name: "Sourcery"

description: 'A GitHub Action for running Sourcery.'

inputs:
  token:
    description: "The Sourcery token for logging in."
    required: true
  options:
    description:
      "Options passed to Sourcery. Run `sourcery review --help` to see available options. Default:
      '--check'"
    required: false
    default: "--check"
  src:
    description: "Path to run Sourcery on. Default: '.'"
    required: false
    default: "."
  # version:
  #   description: 'Python Version specifier (PEP440) - e.g. "0.12.8"'
  #   required: false
  #   default: ""

runs:
  using: composite
  steps:
    - run: |
        # TODO: maybe support inputting the version here
        python3 -m pip install sourcery-cli
        sourcery login --token ${{ inputs.token }}
        sourcery review ${{ inputs.options }} ${{ inputs.src }}
      shell: bash
