name: "Sourcery"

description: 'A GitHub Action for running Sourcery.'

inputs:
  token:
    description: "The Sourcery token for logging in."
    required: true
  options:
    description:
      "Options passed to Sourcery. Run `sourcery review --help` to see available options. Default:
      '--check'"
    required: false
    default: "--check"
  base_ref:
    description: |
      Reference to compare the current branch with.
      # TODO: much better explanation here, please
    required: false
    default: ""
  version:
    description: 'Sourcery version - e.g. "0.12.8". Default: latest.'
    required: false
    default: ""

runs:
  using: composite
  steps:
    - run: |
        if [ "${{ inputs.version }}" == "" ]; then
          python3 -m pip install sourcery-cli
        else
          python3 -m pip install sourcery-cli==${{ inputs.version }}
        fi
        
        sourcery login --token ${{ inputs.token }}

        if [ "${{ inputs.base_ref }}" == "" ]; then
          sourcery review ${{ inputs.options }} .
        else
          git diff ${{ inputs.base_ref }} --diff-filter=AMR --name-only | xargs sourcery review  ${{ inputs.options }}
        fi
      shell: bash
